#ifndef ESP_SDK_VERSION_H
#define ESP_SDK_VERSION_H

#define ESP_SDK_VERSION_MAJOR   3
#define ESP_SDK_VERSION_MINOR   0
#define ESP_SDK_VERSION_PATCH   4

#define ESP_SDK_VERSION_NUMBER 0x030004
#define ESP_SDK_VERSION_STRING  "3.0.4"

#endif
