#ifndef ESP_SDK_VERSION_H
#define ESP_SDK_VERSION_H

#define ESP_SDK_VERSION_MAJOR   3
#define ESP_SDK_VERSION_MINOR   1
#define ESP_SDK_VERSION_PATCH   0

#define ESP_SDK_VERSION_NUMBER 0x030100
#define ESP_SDK_VERSION_STRING  "3.1.0"

#endif
