#ifndef ESP_SDK_VERSION_H
#define ESP_SDK_VERSION_H

#define ESP_SDK_VERSION_MAJOR   3
#define ESP_SDK_VERSION_MINOR   0
#define ESP_SDK_VERSION_PATCH   1

#define ESP_SDK_VERSION_NUMBER 0x030001
#define ESP_SDK_VERSION_STRING  "3.0.1"

#endif
